blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/discussions
    about: Please ask and answer questions here.
