name: Feature Request
description: Suggest an idea for this project

body:
  - type: markdown
    attributes:
      value: Feature
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe, what you want to be added!
      description: >-
        A clear and concise description of what the feature is about.

  - type: textarea
    validations:
      required: true
    attributes:
      value: 
      label: Describe the solution you'd like
      description: >-
        A clear and concise description of what you want to happen.

  - type: textarea
    validations:
      required: true
    attributes:
      value: |
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    validations:
      required: true
    attributes:
      value:
      label: Additional Information
      description: >-
        Add any other context about the problem here. E.g. Screenshots
