name: Feature Request
description: Suggest an idea for this project!
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: markdown
    id: title
    attributes:
      value: Fill out the form to enter a feature request!

  - type: textarea
    id: to_be_added
    validations:
      required: true
    attributes:
      label: Describe, what you want to be added!
      description: >-
        A clear and concise description of what the feature is about.

  - type: textarea
    id: solution  
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like
      description: >-
        A clear and concise description of what you want to happen.

  - type: textarea
    id: describtion
    validations:
      required: true
    attributes:
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional_info  
    validations:
      required: true
    attributes:
      label: Additional Information
      description: >-
        Add any other context about the feature here (e.g. screenshots).
