'use strict';

module.exports = {
    "timer_now": { "en": "just now", "de": "soeben", "ru": "прямо сейчас", "pt": "agora mesmo", "nl": "net nu", "fr": "juste maintenant", "it": "proprio adesso", "es": "En este momento", "pl": "właśnie", "uk": "прямо зараз", "zh-cn": "现在" },
    "timer_few_seconds": { "en": "a few seconds ago", "de": "vor ein paar Sekunden", "ru": "несколько секунд назад", "pt": "Alguns segundos atrás", "nl": "een paar seconden geleden", "fr": "il ya quelques secondes", "it": "qualche secondo fa", "es": "hace unos segundos", "pl": "Kilka sekund temu", "uk": "кілька секунд тому", "zh-cn": "几秒钟前" },
    "timer_second_ago": { "en": "%s second ago", "de": "Vor %s Sekunde", "ru": "%s секунды назад", "pt": "%s segundo atrás", "nl": "%s seconde geleden", "fr": "il y a %s seconde", "it": "%s secondo fa", "es": "Hace %s segundo", "pl": "%s sekund temu", "uk": "%s секунд тому", "zh-cn": "%s 秒前" },
    "timer_seconds_ago": { "en": "%s seconds ago", "de": "Vor %s Sekunden", "ru": "%s секунд назад", "pt": "%s segundos atrás", "nl": "%s seconden geleden", "fr": "il y a %s secondes", "it": "%s secondi fa", "es": "hace %s segundos", "pl": "%s sekund temu", "uk": "%s секунд тому", "zh-cn": "%s 秒前" },
    "timer_few_minutes": { "en": "a few minutes ago", "de": "vor ein paar Minuten", "ru": "Несколько минут назад", "pt": "há alguns minutos atrás", "nl": "een paar minuten geleden", "fr": "il y a quelques minutes", "it": "pochi minuti fa", "es": "Hace pocos minutos", "pl": "kilka minut temu", "uk": "кілька хвилин тому", "zh-cn": "几分钟前" },
    "timer_minute_ago": { "en": "%s minute ago", "de": "Vor %s Minute", "ru": "%s минуту назад", "pt": "%s minuto atrás", "nl": "%s minuut geleden", "fr": "Il y a %s minute", "it": "%s minuto fa", "es": "hace %s minuto", "pl": "%s minut temu", "uk": "%s хвилин тому", "zh-cn": "%s 分钟前" },
    "timer_minutes_ago": { "en": "%s minutes ago", "de": "Vor %s Minuten", "ru": "%s минут назад", "pt": "%s minutos atrás", "nl": "%s minuten geleden", "fr": "il y a %s minutes", "it": "%s minuti fa", "es": "hace %s minutos", "pl": "%s minut temu", "uk": "%s хвилин тому", "zh-cn": "%s 分钟前" },
    "timer_few_hours": { "en": "a few hours ago", "de": "vor ein paar Stunden", "ru": "несколько часов назад", "pt": "há algumas horas atrás", "nl": "een paar uur geleden", "fr": "quelques heures plus tôt", "it": "Alcune ore fa", "es": "hace unas horas", "pl": "kilka godzin temu", "uk": "кілька годин тому", "zh-cn": "几个小时前" },
    "timer_hour_ago": { "en": "%s hour ago", "de": "Vor %s Stunde", "ru": "%s час назад", "pt": "%s hora atrás", "nl": "%s uur geleden", "fr": "Il y a %s heure", "it": "%s ora fa", "es": "hace %s hora", "pl": "%s godzinę temu", "uk": "%s годин тому", "zh-cn": "%s 小时前" },
    "timer_hours_ago": { "en": "%s hours ago", "de": "Vor %s Stunden", "ru": "%s часов назад", "pt": "%s horas atrás", "nl": "%s uur geleden", "fr": "Il y a %s heures", "it": "%s ore fa", "es": "hace %s horas", "pl": "%s godzin temu", "uk": "%s годин тому", "zh-cn": "%s 小时前" },
    "on": { "en": "On", "de": "An", "ru": "На", "pt": "Sobre", "nl": "Op", "fr": "Sur", "it": "SU", "es": "En", "pl": "NA", "uk": "Увімкнено", "zh-cn": "在" },
    "off": { "en": "Off", "de": "Aus", "ru": "Выключенный", "pt": "Desligado", "nl": "Uit", "fr": "Désactivé", "it": "Spento", "es": "Apagado", "pl": "Wyłączony", "uk": "Вимкнено", "zh-cn": "离开" },
};