name: Reviewdog
on: [pull_request, push]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
      
      - name: eslint
        uses: reviewdog/action-eslint@v1
        env: 
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN || github.token }}
        with:
          github_token: ${{ secrets.AUTO_MERGE_TOKEN || github.token }}
          reporter: github-check
          eslint_flags: '. --ignore-pattern doc/'
